[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL-Token 2022 Integration Tests"
edition = "2021"
license = "Apache-2.0"
name = "lpl-token-2022-test"
repository = "https://github.com/gaokanxu/lumos"
version = "0.0.1"

[features]
test-sbf = ["zk-ops"]
default = ["zk-ops"]
zk-ops = []

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = "0.1.77"
borsh = { version = "1.5.1", features = ["unstable__schema"] }
futures-util = "0.3.29"
test-case = "3.3.1"

lumos-program = { path = "../../../lumos/sdk/program" }
lumos-program-test = { path = "../../../lumos/program-test" }
lumos-sdk = { path = "../../../lumos/sdk" }

lpl-associated-token-account = { path = "../../associated-token-account/program" }
lpl-memo = { path = "../../memo/program" }
lpl-pod = { path = "../../libraries/pod" }
lpl-token-2022 = { path = "../../token/program-2022" }
lpl-instruction-padding = { path = "../../instruction-padding/program" }
lpl-tlv-account-resolution = { path = "../../libraries/tlv-account-resolution" }
lpl-token-client = { path = "../../token/client" }
lpl-token-group-interface = { path = "../../token-group/interface" }
lpl-token-metadata-interface = { path = "../../token-metadata/interface" }
lpl-transfer-hook-example = { path = "../../token/transfer-hook/example" }
lpl-transfer-hook-interface = { path = "../../token/transfer-hook/interface" }

