[package]
name = "lpl-token-swap-fuzz"
version = "0.0.1"
description = "Lumos Program Library Token Swap Fuzzer"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
honggfuzz = "0.5"
arbitrary = "1.3.2"

lumos-program = { path = "../../../../lumos/sdk/program" }

lpl-math = { path = "../../../libraries/math" }
lpl-token = { path = "../../../token/program" }
lpl-token-swap = { path = "../../../token-swap/program" }

[[bin]]
name = "token-swap-instructions"
path = "src/instructions.rs"
test = false
doc = false
