[package]
name = "lpl-transfer-hook-example"
version = "0.6.0"
description = "Lumos Program Library Transfer Hook Example Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["forbid-additional-mints"]
no-entrypoint = []
test-sbf = []
forbid-additional-mints = []

[dependencies]
arrayref = "0.3.8"

lumos-program = { path = "../../../../lumos/sdk/program" }
lumos-sdk = { path = "../../../../lumos/sdk" }

lpl-tlv-account-resolution = { path = "../../../libraries/tlv-account-resolution" }
lpl-token-2022 = { path = "../../../token/program-2022" }
lpl-transfer-hook-interface = { path = "../../../token/transfer-hook/interface" }
lpl-type-length-value = { path = "../../../libraries/type-length-value" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
