[package]
name = "test-client"
version = "0.1.0"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
publish = false
edition = "2021"

# Used to ensure that SPL programs are buildable by external clients

[dependencies]
lumos-sdk = { path = "../../../lumos/sdk" }
lpl-memo = { path = "../../memo/program" }
lpl-token = { path = "../../token/program" }
lpl-token-swap = { path = "../../token-swap/program" }
