[package]
name = "lpl-token-lending"
version = "0.2.0"
description = "Lumos Program Library Token Lending"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = "0.3.8"
bytemuck = { git = "https://github.com/gaokanxu/bytemuck.git", branch = "main", package = "bytemuck", features = ["derive"] }
num-derive = "0.4"
num-traits = { version = "0.2", features = ["i128"] }
thiserror = "1.0.57"
uint = "0.9.5"
assert_matches = "1.5.0"
proptest = "1.4"

lumos-program = { path = "../../../lumos/sdk/program" }
lumos-sdk = { path = "../../../lumos/sdk" }
lpl-token = { path = "../../token/program" }

[lib]
crate-type = ["cdylib", "lib"]
