[package]
name = "lpl-token-metadata-example"
version = "0.3.0"
description = "Lumos Program Library Token Metadata Example Program"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
test-case = "3.3.1"

lumos-program = { path = "../../../lumos/sdk/program" }
lumos-sdk = { path = "../../../lumos/sdk" }

lpl-token-2022 = { path = "../../token/program-2022" }
lpl-token-metadata-interface = { path = "../../token-metadata/interface" }
lpl-type-length-value = { path = "../../libraries/type-length-value" }
lpl-pod = { path = "../../libraries/pod" }
lpl-token-client = { path = "../../token/client" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
