[package]
name = "lpl-token-confidential-transfer-proof-test"
version = "0.0.1"
description = "Lumos Program Library Confidential Transfer Proof Test"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
thiserror = "1.0.63"

curve25519-dalek = { path = "../../../../curve25519-dalek/curve25519-dalek", features = ["alloc", "precomputed-tables", "zeroize"] }
lumos-zk-token-sdk = { path = "../../../../lumos/zk-token-sdk" }
lpl-token-confidential-transfer-proof-extraction = { path = "../../confidential-transfer/proof-extraction" }
lpl-token-confidential-transfer-proof-generation = { path = "../../confidential-transfer/proof-generation" }
