[package]
name = "lpl-token-confidential-transfer-ciphertext-arithmetic"
version = "0.1.0"
description = "Lumos Program Library Confidential Transfer Ciphertext Arithmetic"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.22.0"
bytemuck = { git = "https://github.com/gaokanxu/bytemuck.git", branch = "main", package = "bytemuck", features = ["derive"] }

lumos-curve25519 = { path = "../../../../lumos/curves/curve25519" }
curve25519-dalek = { path = "../../../../curve25519-dalek/curve25519-dalek", features = ["alloc", "precomputed-tables", "zeroize"] }
lumos-zk-token-sdk = { path = "../../../../lumos/zk-token-sdk" }

[dev-dependencies]
lpl-token-confidential-transfer-proof-generation = { path = "../../../token/confidential-transfer/proof-generation" }

[lib]
crate-type = ["cdylib", "lib"]
