[package]
name = "lpl-token-upgrade"
version = "0.1.1"
description = "Lumos Program Library Token Upgrade"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
num-derive = "0.4"
num-traits = { version = "0.2", features = ["i128"] }
num_enum = "0.7.2"
thiserror = "1.0.57"
test-case = "3.3.1"

lumos-program = { path = "../../../lumos/sdk/program" }
lumos-sdk = { path = "../../../lumos/sdk" }
lpl-token = { path = "../../token/program" }
lpl-token-client = { path = "../../token/client" }
lpl-token-2022 = { path = "../../token/program-2022" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
