[package]
name = "lpl-token-swap"
version = "3.0.0"
description = "Lumos Program Library Token Swap"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = "0.3.8"
enum_dispatch = "0.3.13"
num-derive = "0.4"
num-traits = { version = "0.2", features = ["i128"] }
thiserror = "1.0.57"
arbitrary = "1.3.2"
roots = "0.0.8"
proptest = "1.4"
test-case = "3.3.1"

lumos-program = { path = "../../../lumos/sdk/program" }
lumos-sdk = { path = "../../../lumos/sdk" }

lpl-math = { path = "../../libraries/math" }
lpl-token = { path = "../../token/program" }
lpl-token-2022 = { path = "../../token/program-2022" }


[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
