[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "LPL-Token Command-line Utility"
edition = "2021"
homepage = "https://spl.lumos.com/token"
license = "Apache-2.0"
name = "lpl-token-cli"
repository = "https://github.com/gaokanxu/lumos"
version = "4.0.0"

[build-dependencies]
walkdir = "2"

[dependencies]
base64 = "0.22.0"
clap = { version = "4.5.15", features = ["cargo"] }
console = "0.15.8"
futures = "0.3.30"
serde = { version = "1.0.204", features = ["derive"] }
serde_derive = "1.0.103"
serde_json = "1.0.114"
strum = "0.24"
strum_macros = "0.24"
tokio = { git = "https://github.com/gaokanxu/tokio.git", branch = "main", package = "tokio" }

lumos-account-decoder = { path = "../../../lumos/account-decoder" }
lumos-clap-utils = { path = "../../../lumos/clap-utils" }
lumos-cli-config = { path = "../../../lumos/cli-config" }
lumos-cli-output = { path = "../../../lumos/cli-output", optional = true}
lumos-client = { path = "../../../lumos/client" }
lumos-logger = { path = "../../../lumos/logger" }
lumos-remote-wallet = { path = "../../../lumos/remote-wallet" }
lumos-sdk = { path = "../../../lumos/sdk" }
lumos-transaction-status = { path = "../../../lumos/transaction-status" }

lpl-token = { path = "../../token/program" }
lpl-token-2022 = { path = "../../token/program-2022" }
lpl-token-client = { path = "../../token/client" }
lpl-token-metadata-interface = { path = "../../token-metadata/interface" }
lpl-token-group-interface = { path = "../../token-group/interface" }
lpl-associated-token-account = { path = "../../associated-token-account/program" }
lpl-memo = { path = "../../memo/program" }


[dev-dependencies]
lumos-test-validator = { path = "../../../lumos/test-validator" }
assert_cmd = "2.0"
libtest-mimic = "0.7"
serial_test = "2.0.0"
tempfile = "3.10.1"

[[bin]]
name = "lpl-token"
path = "src/main.rs"

[[test]]
name = "command"
path = "tests/command.rs"
harness = false

[features]
default = ["display"]
display = ["lumos-cli-output"]

