[package]
name = "lpl-token-wrap"
version = "0.1.0"
description = "Lumos Program Library Token Wrap"
authors = ["Lumos Maintainers <maintainers@lumos.foundation>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytemuck = { git = "https://github.com/gaokanxu/bytemuck.git", branch = "main", package = "bytemuck", features = ["derive"] }
num_enum = "0.7.2"
thiserror = "1.0.57"

lumos-program = { path = "../../../lumos/sdk/program" }
lpl-associated-token-account = { path = "../../associated-token-account/program" }
lpl-token = { path = "../../token/program" }
lpl-token-2022 = { path = "../../token/program-2022" }


[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
