[package]
name = "lpl-token-2022"
version = "4.0.1"
description = "Lumos Program Library Token 2022"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[dependencies]
arrayref = "0.3.7"
num-derive = "0.4"
num-traits = { version = "0.2", features = ["i128"] }
num_enum = "0.7.2"
thiserror = "1.0.57"
serde = { version = "1.0.204", features = ["derive"] }
serde_with = "2.3.3"
base64 = "0.22.0"

lazy_static = "1.5.0"
proptest = "1.4"
serial_test = "2.0.0"
serde_json = "1.0.114"

bytemuck = { git = "https://github.com/gaokanxu/bytemuck.git", branch = "main", package = "bytemuck", features = ["derive"] }
security-txt = { git = "https://github.com/gaokanxu/security-txt.git", branch = "main", package = "security-txt" }

lumos-program = { path = "../../../lumos/sdk/program" }
lumos-sdk = { path = "../../../lumos/sdk" }
lumos-zk-token-sdk = { path = "../../../lumos/zk-token-sdk" }

lpl-memo = { path = "../../memo/program" }
lpl-token-group-interface = { path = "../../token-group/interface" }
lpl-token-metadata-interface = { path = "../../token-metadata/interface" }
lpl-transfer-hook-interface = { path = "../../token/transfer-hook/interface" }
lpl-type-length-value = { path = "../../libraries/type-length-value" }
lpl-pod = { path = "../../libraries/pod" }
lpl-tlv-account-resolution = { path = "../../libraries/tlv-account-resolution" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

