[package]
name = "lpl-token-upgrade-cli"
version = "0.1.1"
description = "SPL Token Upgrade Command-line Utility"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = { version = "4.5.15", features = ["cargo"] }
futures-util = "0.3.29"

tokio = { git = "https://github.com/gaokanxu/tokio.git", branch = "main", package = "tokio" }

lumos-clap-v3-utils = { path = "../../../lumos/clap-v3-utils" }
lumos-cli-config = { path = "../../../lumos/cli-config" }
lumos-client = { path = "../../../lumos/client" }
lumos-logger = { path = "../../../lumos/logger" }
lumos-remote-wallet = { path = "../../../lumos/remote-wallet" }
lumos-sdk = { path = "../../../lumos/sdk" }

lpl-associated-token-account = { path = "../../associated-token-account/program" }
lpl-token = { path = "../../token/program" }
lpl-token-2022 = { path = "../../token/program-2022" }
lpl-token-client = { path = "../../token/client" }
lpl-token-upgrade = { path = "../../token-upgrade/program" }

[[bin]]
name = "lpl-token-upgrade"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
