[package]
name = "lpl-token-confidential-transfer-proof-extraction"
version = "0.1.0"
description = "Lumos Program Library Confidential Transfer Proof Extraction"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
thiserror = "1.0.57"

bytemuck = { git = "https://github.com/gaokanxu/bytemuck.git", branch = "main", package = "bytemuck", features = ["derive"] }
curve25519-dalek = { path = "../../../../curve25519-dalek/curve25519-dalek", features = ["alloc", "precomputed-tables", "zeroize"] }
lumos-zk-token-sdk = { path = "../../../../lumos/zk-token-sdk" }

[lib]
crate-type = ["cdylib", "lib"]
