[package]
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
description = "SPL Transfer Hook Command-line Utility"
edition = "2021"
homepage = "https://spl.lumos.com/token"
license = "Apache-2.0"
name = "lpl-transfer-hook-cli"
repository = "https://github.com/gaokanxu/lumos"
version = "0.2.0"

[dependencies]
clap = { version = "4.5.15", features = ["cargo"] }
futures-util = "0.3.29"
strum = "0.24"
strum_macros = "0.24"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"

tokio = { git = "https://github.com/gaokanxu/tokio.git", branch = "main", package = "tokio" }

lumos-clap-v3-utils = { path = "../../../../lumos/clap-v3-utils" }
lumos-cli-config = { path = "../../../../lumos/cli-config" }
lumos-client = { path = "../../../../lumos/client" }
lumos-logger = { path = "../../../../lumos/logger" }
lumos-remote-wallet = { path = "../../../../lumos/remote-wallet" }
lumos-sdk = { path = "../../../../lumos/sdk" }

lpl-tlv-account-resolution = { path = "../../../libraries/tlv-account-resolution" }
lpl-transfer-hook-interface = { path = "../../../token/transfer-hook/interface" }

[dev-dependencies]
lumos-test-validator = { path = "../../../../lumos/test-validator" }
lpl-token-2022 = { path = "../../../token/program-2022" }
lpl-token-client = { path = "../../../token/client" }
lpl-transfer-hook-example = { path = "../../../token/transfer-hook/example" }

[[bin]]
name = "lpl-transfer-hook"
path = "src/main.rs"
