[package]
name = "lpl-transfer-hook-interface"
version = "0.7.0"
description = "Lumos Program Library Transfer Hook Interface"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = "0.3.8"
bytemuck = { git = "https://github.com/gaokanxu/bytemuck.git", branch = "main", package = "bytemuck", features = ["derive"] }
lumos-program = { path = "../../../../lumos/sdk/program" }
lpl-discriminator = { path = "../../../libraries/discriminator" }
lpl-program-error = { path = "../../../libraries/program-error" }
lpl-tlv-account-resolution = { path = "../../../libraries/tlv-account-resolution" }
lpl-type-length-value = { path = "../../../libraries/type-length-value" }
lpl-pod = { path = "../../../libraries/pod" }

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
tokio = { version = "1.39.1", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
