[package]
name = "lpl-token-metadata-interface"
version = "0.4.0"
description = "Lumos Program Library Token Metadata Interface"
authors = ["Gao Kanxu <gaokanxu@gmail.com>"]
repository = "https://github.com/gaokanxu/lumos"
license = "Apache-2.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.1", features = ["unstable__schema"] } 
serde = { version = "1.0.204", features = ["derive"] } 
serde_json = "1.0.114"

lumos-program = { path = "../../../lumos/sdk/program" }
lpl-discriminator = { path = "../../libraries/discriminator" }
lpl-program-error = { path = "../../libraries/program-error" }
lpl-type-length-value = { path = "../../libraries/type-length-value" }
lpl-pod = { path = "../../libraries/pod" }


[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
